---
- name: Set CLI color based on environment
  set_fact:
    ps1_prompt: "{{ '\\[\\033[01;31m\\]\\u@\\h:\\w\\$ \\[\\033[00m\\]' if env == 'prod' else '\\[\\033[01;32m\\]\\u@\\h:\\w\\$ \\[\\033[00m\\]' }}"

- name: Backup current .bashrc file
  copy:
    src: "/home/{{ user_name }}/.bashrc"
    dest: "/home/{{ user_name }}/.bashrc.bak"
    remote_src: yes
  when: ansible_facts['user'][user_name]['home'] is defined

- name: Modify the user's .bashrc file to enable color prompt
  lineinfile:
    path: "/home/{{ user_name }}/.bashrc"
    regexp: '^#force_color_prompt=yes'
    line: 'force_color_prompt=yes'
    create: yes

- name: Set custom PS1 prompt in .bashrc
  lineinfile:
    path: "/home/{{ user_name }}/.bashrc"
    regexp: '^PS1='
    line: "PS1='{{ ps1_prompt }}'"
    create: yes

- name: Ensure the .bashrc file has correct permissions
  file:
    path: "/home/{{ user_name }}/.bashrc"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'

- name: Apply changes by reloading .bashrc
  shell: source /home/{{ user_name }}/.bashrc
  become: false
  when: ansible_facts['user'][user_name]['home'] is defined
